[net]
git-fetch-with-cli = true

[target.'cfg(target_arch = "aarch64")']
rustflags = ["--cfg", "aes_armv8"]

[target.'cfg(any(target_arch = "x86_64", target_arch = "x86))']
rustflags = ["-Ctarget-feature=+aes,+ssse3"]
