[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'

[invariant]
runs = 10
depth = 250
show_metrics = true
failure_persist_dir="./testruns"