[default]
address = "0.0.0.0"
limits = { form = "64 kB", json = "16384 kB", file = "16384 kB" }
log_level = "critical"
temp_dir = "/var/tmp"

[default.shutdown]
ctrlc = true
signals = ["term", "hup"]
grace = 30
mercy = 5