# .github/workflows/deploy-release-ui.yml

name: Deploy Release Info Store UI

on:
  # Manually trigger this workflow from any branch
  workflow_dispatch:
    inputs:
      source_branch:
        description: 'Branch to deploy from (UI code in lit-ansible)'
        required: true
        default: 'master'

  # Automatically trigger when a new GitHub Release is published
  release:
    types: [published]

# Specify permissions for the GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout UI Code from lit-ansible
        uses: actions/checkout@v5
        with:
          repository: 'LIT-Protocol/lit-ansible'
          path: 'lit-ansible'
          token: ${{ secrets.ABHI_GH_PAT }}
          # When triggered by a release, use the 'master' branch for UI code.
          # When triggered manually, use the branch specified in the input.
          ref: ${{ github.event.inputs.source_branch || 'master' }}

      - name: Checkout Release Data from lit-peer
        uses: actions/checkout@v5
        with:
          repository: 'LIT-Protocol/lit-peer'
          ref: 'releases-info'
          path: 'lit-ansible/release-data-store'

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'

      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: lit-ansible/infrastructure/release-info-store/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('lit-ansible/infrastructure/release-info-store/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm clean-install
        working-directory: lit-ansible/infrastructure/release-info-store

      - name: Build Next.js Site
        run: npm run build
        working-directory: lit-ansible/infrastructure/release-info-store

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: lit-ansible/infrastructure/release-info-store/out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
